#!/usr/bin/env python3
"""
Usage: nts (-a <text> ... | -c <category> <text> ... | -r <line> | -h | -s)

Options:
    -h, --help      this help screen
    -a, --add       adds text to the note database
    -c, --cat       adds text in a category (first word is the category)
    -r, --rm        delete item at number (text or entire category)
    -s, --settings  show the settings

"""
from docopt import docopt

import sqlite3
import os


def add_txt(text):
    pass


def add_cat(category, text):
    pass


def rm_item(nbr):
    pass


def init_db():
    pass


def get_cur():
    pass


if __name__ == "__main__":
    args = docopt(__doc__, help=False, options_first=True)
    print(args)
